CREATE TABLE IF NOT EXISTS public.producers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 2 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    brand text COLLATE pg_catalog."default" NOT NULL,
    country text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT producers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.producers
    OWNER to postgres;